### ISSUE TITLE
Log severity with Emoji

### ISSUE THREAD

**Issue by noamtamim** [delba/Log#21]
I want my logger to include the following emoji symbols with the log:
ERROR: ❗️
WARNING: ❕

In other words, whenever an error is logged, the logger will also include "❗️" in the log.

Is that possible by customizing the formatter, or does it require a deeper change?

**Comment by surajthomask** [comment]
I have added this in my fork, feel free to use it, if you would like to.

https://github.com/surajthomask/Log

**Comment by delba** [comment]
Thanks for PR @surajthomask, I'll review it soon !
@noamtamim we'll keep the conversation going here https://github.com/delba/Log/pull/25
