### ISSUE TITLE
For UIViewController,as property init,crash 

### ISSUE THREAD

**Issue by gityoung** [delba/Log#23]
I define a global variable as property in the UIViewController  ，Crashed when use in Closures，Crash reason unexpectedly found nil while unwrapping an Optional value
in Formatters.swift -226

**Comment by delba** [comment]
Hi @gityoung, the project has been updated to the latest Swift version and it should fix this issue.
See this commit https://github.com/delba/Log/commit/13e60e3f2597a6d8a3c2bfe9365751cd9d3ceddf
