### ISSUE TITLE
Carthage + Xcode 10.2.1 : Task failed with exit code 65

### ISSUE THREAD

**Issue by JoseTovar94** [delba/Log#32]
Step to reproduce :

Run carthage update --platform iOS on your project
Get this error :
```
*** Building scheme "Log iOS" in Log.xcodeproj
Build Failed
Task failed with exit code 65....
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details:
```

Did someone found a solution ?

**Comment by delba** [comment]
Hi @JoseTovar94, the project has been updated to the latest Swift version, it should fix the issue.
